name: Manual .NET Build

on:
  workflow_dispatch:

jobs:
  print-runtime-context:
    runs-on: ubuntu-latest

    steps:
      - name: âŒš Start build process
        run: echo "Build process has started..."

      - &echo-template
        name: Echo template
        run: echo "This is a reusable step."
        shell: bash

      - name: Show runtime context
        run: |
          echo "ğŸ› ï¸ Runner OS: ${{ runner.os }}"
          echo "ğŸ“¦ Repository: ${{ github.repository }}"
          echo "ğŸ‰ Workflow: ${{ github.workflow }}"
          echo "ğŸš€ Triggered by: ${{ github.event_name }}"
          echo "ğŸ§‘â€ğŸ¦³ Actor: ${{ github.actor }}"
          echo "ğŸ¦µ Run number: ${{ github.run_number }}"
          echo "ğŸŒ´ Branch: ${{ github.ref }}"

      - *echo-template

  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Install .NET 9
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '9.0.x'

      - name: Build project
        run: dotnet build CleanCodeDevOpsApp/CleanCodeDevOpsApp.csproj

      - name: Run code
        run: dotnet run --project CleanCodeDevOpsApp/CleanCodeDevOpsApp.csproj
